### ISSUE TITLE
Can you provide an example or guide about how to run these functions?

### ISSUE THREAD

**Issue by baikangbo** [pulp-platform/pulp-transformer#1]
Thank you for sharing, these functions seem very useful to me. But could you provide some examples or a guide so that others can actually run this code? Just having the kernel function definitions makes it very difficult for others to run or use this code

**Comment by Victor-Jung** [comment]
Hi @baikangbo, sorry for the delay in getting back to you. In the README, you can find an example explaining how to use the Kernel Test Harness. You need to install the GAP SDK, and then you will be able to run the kernels on the GVSoC simulator. 

If you're looking at running DNNs on our platform, I redirect you to our recently open-sourced compiler [Deeploy](https://github.com/pulp-platform/Deeploy). It uses kernel libraries such as [PULP-NN](https://github.com/pulp-platform/pulp-nn) to execute DNN layers and generates the tiling and data movement code for you.

Best,
Victor
