### ISSUE TITLE
DumpO for ARM

### ISSUE THREAD

**Issue by PriceWang** [pulp-platform/pulp-transformer#3]
Thanks for your sharing. I'm interested in the tool (DumpO) you used to compile the integerized ONNX graph into C code. Can you provide any information about this tool? Or it's a non-reproducible part?

**Comment by Victor-Jung** [comment]
Hi @PriceWang, sorry for the long reply time, I didn't receive a ping from GitHub. We open-sourced our in-house ONNX-to-C-Code compiler, it's not named DumpO anymore but [Deeploy](https://github.com/pulp-platform/Deeploy).

DumpO was basically a prototype targeting ARM platforms such as Cortex-M4. Deeploy currently has 4 backends:
- ARM Cortex
- PULP Processors
- Generic C Code
- [Mempool](https://github.com/pulp-platform/mempool)

Best,
Victor
